### ISSUE TITLE
Keyboard opens itself when toggling a checklist

### ISSUE THREAD

**Issue by super-lurker** [maelchiotti/LocalMaterialNotes#107] opened 2024-06-29 13:25 UTC
Every time I check a task box on my list, the on-screen keyboard pops up every time. Either provide an option to turn off this behavior or create a dedicated note mode for task lists.

**Comment by maelchiotti** [comment] 2024-06-29 15:03
Hi, thank you for opening this issue.

This is a bug of the [fleather](https://github.com/fleather-editor/fleather) editor library, not a feature. I agree it is annoying. I opened an [issue](https://github.com/fleather-editor/fleather/issues/301) on their repository some time ago.

I don't plan on adding tasklists only notes. So I'll ask the fleather maintainers if they can think of a temporary fix. In the meantime, there is sadly nothing I can do.

**Comment by maelchiotti** [comment] 2024-06-30 09:17
I'll keep this open as I wait for fleather feedback.

**Comment by emavgl** [comment] 2024-07-13 11:37
Hi, thanks for app. I really like it. I experience a similar issue: after finishing to type a note, I type the back button but it does not go back, but opens the keyboard instead.

**Comment by maelchiotti** [comment] 2024-07-13 12:03
Hi @emavgl, thank you for the report and thank you for enjoying the app! This seems weird indeed. Do you think you could record your screen so I can see the bug happening?

**Comment by emavgl** [comment] 2024-07-13 12:16
Sure, you can check the video here

https://1drv.ms/v/s!Aj7jAM1nltbampdt2kb0Q0es9crFgw

I am using the gesture as "go back button".

**Comment by maelchiotti** [comment] 2024-07-13 12:27
Thank you. What smartphone do you have and what android version does it run on?

**Comment by emavgl** [comment] 2024-07-13 12:29
Samsung A52s, Android 14 (One UI 6.1)

**Comment by maelchiotti** [comment] 2024-07-13 12:38
Do you use predictive back navigation?

**Comment by emavgl** [comment] 2024-07-13 13:06
I don't know what it is to be honest. No special options

**Comment by maelchiotti** [comment] 2024-07-15 10:28
Hi @emavgl, I did reproduce your issue, and reported it to the fleather theme (this is the text editor used for the notes). Since it's not the same issue as the one with the checkboxes, I created #122. Thank you for your report!

**Comment by maelchiotti** [comment] 2024-07-18 10:13
@super-lurker this has been fixed by the fleather team, the fix will be included in the next release!

**Closed** 2024-07-18 10:13 UTC
Labels: bug
